# Default level for all loggers
org.slf4j.simpleLogger.defaultLogLevel=info

# Enable DEBUG for our application only
org.slf4j.simpleLogger.log.com.dahla=debug

# Show timestamp
org.slf4j.simpleLogger.showDateTime=true

# Timestamp format
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss.SSS

# Show log level
org.slf4j.simpleLogger.showLogName=true

# Show thread name
org.slf4j.simpleLogger.showThreadName=true

# Show short logger name
org.slf4j.simpleLogger.showShortLogName=true