package com.dahla.dto;

public class PlayerAction {
    // Jackson needs these fields to be public (or have getters/setters) to read the JSON
    public String action; // e.g., "PLAY_CARD"
    public String suit;   // e.g., "SPADES"
    public String rank;   // e.g., "TEN"

    // Lobby actions
    public String playerName;
    public String playerToken; // The secret ID generated by the browser
    public String roomCode;    // The 4-digit invite code (e.g., "A7X2")
    public RoomSettings settings; // 🌟 NEW: The custom rules object sent from the frontend



    // Default constructor is required by Jackson for JSON deserialization
    public PlayerAction() {}
}